/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EditProfileModal`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Camera`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Inventory`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Login`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Schemes`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/EditProfileModal`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Camera`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Inventory`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Schemes`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/explore${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../components/EditProfileModal${`?${string}` | `#${string}` | ''}` | `/pages/Profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/pages/Camera${`?${string}` | `#${string}` | ''}` | `/pages/Dashboard${`?${string}` | `#${string}` | ''}` | `/pages/Inventory${`?${string}` | `#${string}` | ''}` | `/pages/Login${`?${string}` | `#${string}` | ''}` | `/pages/Onboarding${`?${string}` | `#${string}` | ''}` | `/pages/Schemes${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EditProfileModal`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Camera`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Inventory`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Login`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Schemes`; params?: Router.UnknownInputParams; };
    }
  }
}
